<#
.SYNOPSIS
    Bolt Framework - Test Two-Step Initialization Workflow

.DESCRIPTION
    Automated tests for the two-step initialization pattern:
    - Step 1: Init.ps1 (Practice selection + basic config)
    - Step 2: bolt-setup-constitution (file provisioning)

    Tests cover:
    1. Practice "Apps & Infra" workflow
    2. Skill provisioning and constitution merge
    3. Practice "Data & AI" workflow
    4. Custom mode (manual scope selection)
    5. Dry-run mode
    6. Re-provisioning (idempotency)
    7. CI/CD provider skill routing from `cicd.platform`

.PARAMETER TestNumber
    Run specific test (1-6). If not specified, runs all tests.

.PARAMETER KeepTestProjects
    Keep test projects after completion (for manual inspection)

.EXAMPLE
    .\Test-InitFlows.ps1
    # Runs all 7 tests

.EXAMPLE
    .\Test-InitFlows.ps1 -TestNumber 1 -KeepTestProjects
    # Runs only test 1 and keeps the test project
#>

param(
    [int]$TestNumber = 0,
    [switch]$KeepTestProjects
)

# ─── Configuration ────────────────────────────────────────────────────────────

$ErrorActionPreference = "Stop"
$FrameworkRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$TestOutputDir = Join-Path $env:TEMP "bolt-framework-tests"
$PassedTests = 0
$FailedTests = 0
$TestResults = @()

# ─── Logging Functions ────────────────────────────────────────────────────────

function Write-TestHeader { param($msg) Write-Host "`n═══ $msg ═══" -ForegroundColor Cyan }
function Write-TestStep { param($msg) Write-Host "  → $msg" -ForegroundColor Blue }
function Write-TestPass { param($msg) Write-Host "  ✓ $msg" -ForegroundColor Green }
function Write-TestFail { param($msg) Write-Host "  ✗ $msg" -ForegroundColor Red }
function Write-TestWarn { param($msg) Write-Host "  ⚠ $msg" -ForegroundColor Yellow }

# ─── Test Utilities ───────────────────────────────────────────────────────────

function Assert-FileExists {
    param([string]$Path, [string]$Description)
    if (Test-Path $Path) {
        Write-TestPass "$Description exists"
        return $true
    } else {
        Write-TestFail "$Description NOT found: $Path"
        throw "Assertion failed: File not found"
    }
}

function Assert-FileNotExists {
    param([string]$Path, [string]$Description)
    if (-not (Test-Path $Path)) {
        Write-TestPass "$Description does not exist (as expected)"
        return $true
    } else {
        Write-TestFail "$Description exists (unexpected): $Path"
        throw "Assertion failed: File should not exist"
    }
}

function Assert-FileContains {
    param([string]$Path, [string]$Pattern, [string]$Description)
    if (-not (Test-Path $Path)) {
        Write-TestFail "$Description - File not found: $Path"
        throw "Assertion failed: File not found"
    }

    $content = Get-Content $Path -Raw
    if ($content -match $Pattern) {
        Write-TestPass "$Description matches pattern"
        return $true
    } else {
        Write-TestFail "$Description does NOT match pattern: $Pattern"
        throw "Assertion failed: Pattern not found"
    }
}

function New-TestProject {
    param([string]$Name)

    $projectPath = Join-Path $TestOutputDir $Name
    if (Test-Path $projectPath) {
        Remove-Item $projectPath -Recurse -Force
    }
    New-Item -ItemType Directory -Path $projectPath -Force | Out-Null

    Write-TestStep "Created test project: $Name"
    return $projectPath
}

function Remove-TestProject {
    param([string]$Path)

    if (-not $KeepTestProjects -and (Test-Path $Path)) {
        Remove-Item $Path -Recurse -Force
        Write-TestStep "Cleaned up test project"
    }
}

# ─── Test 1: Practice "Apps & Infra" Initialization ───────────────────────────

function Test-01-AppsInfraInit {
    Write-TestHeader "TEST 1: Practice 'Apps & Infra' - Init.ps1 Only"

    try {
        $projectPath = New-TestProject "test-01-apps-infra-init"

        # Simulate Init.ps1 execution with "Apps & Infra" practice
        Write-TestStep "Simulating Init.ps1 with Practice: Apps & Infra"

        # Create basic structure as Init.ps1 would
        $boltDir = Join-Path $projectPath ".boltf"
        $memoryDir = Join-Path $boltDir "memory"
        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null

        # Create basic constitution (as generated by Init.ps1)
        $constitutionPath = Join-Path $memoryDir "constitution.md"
        $basicConstitution = @"
# Project Constitution

> **Two-Step Initialization**: This is a basic constitution generated by Init.ps1.
> Run ``@Bolt Constitution`` to provision files and merge scope-specific constitutions.

## Metadata

- **Practice**: Apps & Infra
- **Active Scopes**: backend, frontend, cloud-platform
- **Project Type**: full-stack (green)
- **Initialized**: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

---

# Article I §1.1 — Active Scopes

The following scopes are active for this project:

- **backend**
- **frontend**
- **cloud-platform**

## Next Steps

1. **Provision Files**: Run ``@Bolt Constitution`` agent
2. **Review**: The skill will merge scope-specific constitutions
3. **Customize**: Edit this constitution to reflect project-specific decisions
"@
        Set-Content -Path $constitutionPath -Value $basicConstitution -Encoding UTF8

        # Create scopes.yaml (as generated by Init.ps1)
        $scopesYamlPath = Join-Path $boltDir "scopes.yaml"
        $scopesYaml = @"
project:
  practice: Apps & Infra
  type: full-stack
  migration-type: green

active-scopes:
  - backend
  - frontend
  - cloud-platform

transversal-scopes:
  - work-management
"@
        Set-Content -Path $scopesYamlPath -Value $scopesYaml -Encoding UTF8

        # Assertions
        Write-TestStep "Verifying Init.ps1 outputs..."
        Assert-FileExists $constitutionPath "Basic constitution"
        Assert-FileContains $constitutionPath "Apps & Infra" "Constitution contains Practice"
        Assert-FileContains $constitutionPath "backend.*frontend.*cloud-platform" "Constitution contains scopes"

        Assert-FileExists $scopesYamlPath "scopes.yaml"
        Assert-FileContains $scopesYamlPath "practice: Apps & Infra" "scopes.yaml contains Practice"

        # Verify .github/ does NOT exist yet (provisioning not run)
        $githubDir = Join-Path $projectPath ".github"
        Assert-FileNotExists $githubDir ".github directory (pre-provisioning)"

        Write-TestPass "TEST 1 PASSED"
        $script:PassedTests++
        $script:TestResults += @{ Test = 1; Name = "Apps & Infra Init"; Status = "PASS" }

        Remove-TestProject $projectPath
    }
    catch {
        Write-TestFail "TEST 1 FAILED: $_"
        $script:FailedTests++
        $script:TestResults += @{ Test = 1; Name = "Apps & Infra Init"; Status = "FAIL"; Error = $_.Exception.Message }
    }
}

# ─── Test 2: bolt-setup-constitution Skill Execution ──────────────────────────

function Test-02-SetupConstitutionSkill {
    Write-TestHeader "TEST 2: bolt-setup-constitution Skill Execution"

    try {
        $projectPath = New-TestProject "test-02-setup-constitution"

        # Setup: Create project structure (as from Test 1)
        Write-TestStep "Setting up initialized project..."

        $boltDir = Join-Path $projectPath ".boltf"
        $memoryDir = Join-Path $boltDir "memory"
        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null

        # Basic constitution
        $constitutionPath = Join-Path $memoryDir "constitution.md"
        Set-Content -Path $constitutionPath -Value "# Project Constitution`n`nPractice: Apps & Infra`n`n# Article I: Active Scopes`n- backend`n- frontend`n- cloud-platform" -Encoding UTF8

        # scopes.yaml
        $scopesYamlPath = Join-Path $boltDir "scopes.yaml"
        $scopesYaml = @"
project:
  practice: Apps & Infra
  type: full-stack

active-scopes:
  - backend
  - frontend
  - cloud-platform

transversal-scopes:
  - work-management
"@
        Set-Content -Path $scopesYamlPath -Value $scopesYaml -Encoding UTF8

        # Execute bolt-setup-constitution skill
        Write-TestStep "Invoking Invoke-BoltSetupConstitution.ps1..."

        $setupScript = Join-Path $FrameworkRoot ".boltf\scripts\powershell\Invoke-BoltSetupConstitution.ps1"

        if (-not (Test-Path $setupScript)) {
            throw "Setup script not found: $setupScript"
        }

        # Execute with output capture
        $output = & $setupScript -ProjectPath $projectPath 2>&1

        # Verify outputs
        Write-TestStep "Verifying provisioning results..."

        # Check constitution merged
        Assert-FileExists $constitutionPath "Merged constitution"
        Assert-FileContains $constitutionPath "Article.*Tech Stack|Article.*Testing|Article.*Security" "Constitution has merged articles"

        # Check provision report
        $reportPath = Join-Path $memoryDir "provision-report.md"
        Assert-FileExists $reportPath "Provision report"
        Assert-FileContains $reportPath "Bolt Setup Constitution - Provision Report" "Report header"
        Assert-FileContains $reportPath "Practice.*Apps & Infra" "Report contains Practice"

        # Check core skills provisioned
        $skillsDir = Join-Path $projectPath ".claude\skills"
        Assert-FileExists $skillsDir "Skills directory"

        $boltFrameworkSkill = Join-Path $skillsDir "bolt-framework\SKILL.md"
        Assert-FileExists $boltFrameworkSkill "bolt-framework skill"

        Write-TestPass "TEST 2 PASSED"
        $script:PassedTests++
        $script:TestResults += @{ Test = 2; Name = "Setup Constitution Skill"; Status = "PASS" }

        Remove-TestProject $projectPath
    }
    catch {
        Write-TestFail "TEST 2 FAILED: $_"
        $script:FailedTests++
        $script:TestResults += @{ Test = 2; Name = "Setup Constitution Skill"; Status = "FAIL"; Error = $_.Exception.Message }
    }
}

# ─── Test 3: Practice "Data & AI" ─────────────────────────────────────────────

function Test-03-DataAIPractice {
    Write-TestHeader "TEST 3: Practice 'Data & AI' Workflow"

    try {
        $projectPath = New-TestProject "test-03-data-ai"

        Write-TestStep "Creating project with Practice: Data & AI"

        $boltDir = Join-Path $projectPath ".boltf"
        $memoryDir = Join-Path $boltDir "memory"
        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null

        # Constitution for Data & AI
        $constitutionPath = Join-Path $memoryDir "constitution.md"
        Set-Content -Path $constitutionPath -Value "# Project Constitution`n`nPractice: Data & AI`n`n# Article I: Active Scopes`n- data`n- ai`n- integration" -Encoding UTF8

        # scopes.yaml for Data & AI
        $scopesYamlPath = Join-Path $boltDir "scopes.yaml"
        $scopesYaml = @"
project:
  practice: Data & AI
  type: data-platform

active-scopes:
  - data
  - ai
  - integration

transversal-scopes:
  - work-management
"@
        Set-Content -Path $scopesYamlPath -Value $scopesYaml -Encoding UTF8

        # Run provisioning
        Write-TestStep "Running bolt-setup-constitution..."
        $setupScript = Join-Path $FrameworkRoot ".boltf\scripts\powershell\Invoke-BoltSetupConstitution.ps1"
        & $setupScript -ProjectPath $projectPath | Out-Null

        # Assertions
        Write-TestStep "Verifying Data & AI specific provisioning..."

        Assert-FileContains $constitutionPath "Data & AI" "Constitution has Data & AI practice"
        Assert-FileContains $constitutionPath "data.*ai.*integration" "Constitution has correct scopes"

        $reportPath = Join-Path $memoryDir "provision-report.md"
        Assert-FileContains $reportPath "Data & AI" "Provision report shows practice"

        Write-TestPass "TEST 3 PASSED"
        $script:PassedTests++
        $script:TestResults += @{ Test = 3; Name = "Data & AI Practice"; Status = "PASS" }

        Remove-TestProject $projectPath
    }
    catch {
        Write-TestFail "TEST 3 FAILED: $_"
        $script:FailedTests++
        $script:TestResults += @{ Test = 3; Name = "Data & AI Practice"; Status = "FAIL"; Error = $_.Exception.Message }
    }
}

# ─── Test 4: Custom Mode (Manual Scope Selection) ─────────────────────────────

function Test-04-CustomMode {
    Write-TestHeader "TEST 4: Custom Mode - Manual Scope Selection"

    try {
        $projectPath = New-TestProject "test-04-custom-mode"

        Write-TestStep "Creating project with Custom practice (manual scopes)"

        $boltDir = Join-Path $projectPath ".boltf"
        $memoryDir = Join-Path $boltDir "memory"
        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null

        # User manually selects: backend, data (no frontend, no cloud-platform)
        $constitutionPath = Join-Path $memoryDir "constitution.md"
        Set-Content -Path $constitutionPath -Value "# Project Constitution`n`nPractice: Custom`n`n# Article I: Active Scopes`n- backend`n- data" -Encoding UTF8

        $scopesYamlPath = Join-Path $boltDir "scopes.yaml"
        $scopesYaml = @"
project:
  practice: Custom
  type: app-only

active-scopes:
  - backend
  - data

transversal-scopes:
  - work-management
"@
        Set-Content -Path $scopesYamlPath -Value $scopesYaml -Encoding UTF8

        # Run provisioning
        Write-TestStep "Running provisioning with custom scopes..."
        $setupScript = Join-Path $FrameworkRoot ".boltf\scripts\powershell\Invoke-BoltSetupConstitution.ps1"
        & $setupScript -ProjectPath $projectPath | Out-Null

        # Verify only backend and data scopes provisioned
        Write-TestStep "Verifying selective provisioning..."

        $reportPath = Join-Path $memoryDir "provision-report.md"
        Assert-FileContains $reportPath "Custom" "Report shows Custom practice"
        Assert-FileContains $reportPath "backend.*data" "Report lists correct scopes"

        Write-TestPass "TEST 4 PASSED"
        $script:PassedTests++
        $script:TestResults += @{ Test = 4; Name = "Custom Mode"; Status = "PASS" }

        Remove-TestProject $projectPath
    }
    catch {
        Write-TestFail "TEST 4 FAILED: $_"
        $script:FailedTests++
        $script:TestResults += @{ Test = 4; Name = "Custom Mode"; Status = "FAIL"; Error = $_.Exception.Message }
    }
}

# ─── Test 5: Dry-Run Mode ──────────────────────────────────────────────────────

function Test-05-DryRunMode {
    Write-TestHeader "TEST 5: Dry-Run Mode (Preview Changes)"

    try {
        $projectPath = New-TestProject "test-05-dryrun"

        Write-TestStep "Setting up project for dry-run test..."

        $boltDir = Join-Path $projectPath ".boltf"
        $memoryDir = Join-Path $boltDir "memory"
        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null

        $constitutionPath = Join-Path $memoryDir "constitution.md"
        $originalConstitution = "# Project Constitution`n`nPractice: Apps & Infra"
        Set-Content -Path $constitutionPath -Value $originalConstitution -Encoding UTF8

        $scopesYamlPath = Join-Path $boltDir "scopes.yaml"
        Set-Content -Path $scopesYamlPath -Value "project:`n  practice: Apps & Infra`nactive-scopes:`n  - backend" -Encoding UTF8

        # Capture file modification time BEFORE dry-run
        $constitutionModTimeBefore = (Get-Item $constitutionPath).LastWriteTime

        # Run in DRY-RUN mode
        Write-TestStep "Running Invoke-BoltSetupConstitution.ps1 -DryRun..."
        $setupScript = Join-Path $FrameworkRoot ".boltf\scripts\powershell\Invoke-BoltSetupConstitution.ps1"
        $output = & $setupScript -ProjectPath $projectPath -DryRun 2>&1

        # Verify NO files were modified
        Write-TestStep "Verifying no files were modified in dry-run..."

        $constitutionModTimeAfter = (Get-Item $constitutionPath).LastWriteTime
        if ($constitutionModTimeBefore -eq $constitutionModTimeAfter) {
            Write-TestPass "Constitution not modified (dry-run respected)"
        } else {
            throw "Constitution was modified during dry-run"
        }

        # Verify output mentions dry-run
        if ($output -match "DRY RUN|dry.run|preview") {
            Write-TestPass "Output indicates dry-run mode"
        } else {
            Write-TestWarn "Output doesn't clearly indicate dry-run (check implementation)"
        }

        # Verify provision report NOT created
        $reportPath = Join-Path $memoryDir "provision-report.md"
        Assert-FileNotExists $reportPath "Provision report (should not exist in dry-run)"

        Write-TestPass "TEST 5 PASSED"
        $script:PassedTests++
        $script:TestResults += @{ Test = 5; Name = "Dry-Run Mode"; Status = "PASS" }

        Remove-TestProject $projectPath
    }
    catch {
        Write-TestFail "TEST 5 FAILED: $_"
        $script:FailedTests++
        $script:TestResults += @{ Test = 5; Name = "Dry-Run Mode"; Status = "FAIL"; Error = $_.Exception.Message }
    }
}

# ─── Test 6: Re-Provisioning (Idempotency) ────────────────────────────────────

function Test-06-Idempotency {
    Write-TestHeader "TEST 6: Re-Provisioning (Idempotency Check)"

    try {
        $projectPath = New-TestProject "test-06-idempotency"

        Write-TestStep "Setting up project for idempotency test..."

        $boltDir = Join-Path $projectPath ".boltf"
        $memoryDir = Join-Path $boltDir "memory"
        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null

        $constitutionPath = Join-Path $memoryDir "constitution.md"
        Set-Content -Path $constitutionPath -Value "# Project Constitution`n`nPractice: Apps & Infra" -Encoding UTF8

        $scopesYamlPath = Join-Path $boltDir "scopes.yaml"
        Set-Content -Path $scopesYamlPath -Value "project:`n  practice: Apps & Infra`nactive-scopes:`n  - backend" -Encoding UTF8

        # First provisioning
        Write-TestStep "Running FIRST provisioning..."
        $setupScript = Join-Path $FrameworkRoot ".boltf\scripts\powershell\Invoke-BoltSetupConstitution.ps1"
        & $setupScript -ProjectPath $projectPath | Out-Null

        # Capture state after first run
        $reportPath = Join-Path $memoryDir "provision-report.md"
        Assert-FileExists $reportPath "Provision report (first run)"
        $firstRunReport = Get-Content $reportPath -Raw

        # Second provisioning (should detect existing files)
        Write-TestStep "Running SECOND provisioning (idempotency check)..."
        $output = & $setupScript -ProjectPath $projectPath 2>&1

        # Verify warnings about existing files
        Write-TestStep "Checking for 'already exists' warnings..."
        if ($output -match "already exist|skipping|preserving") {
            Write-TestPass "Script detected existing files"
        } else {
            Write-TestWarn "No explicit warnings about existing files (check implementation)"
        }

        # Verify no errors occurred
        if ($LASTEXITCODE -eq 0 -or $null -eq $LASTEXITCODE) {
            Write-TestPass "Second run completed without errors"
        } else {
            throw "Second provisioning failed with exit code: $LASTEXITCODE"
        }

        Write-TestPass "TEST 6 PASSED"
        $script:PassedTests++
        $script:TestResults += @{ Test = 6; Name = "Idempotency"; Status = "PASS" }

        Remove-TestProject $projectPath
    }
    catch {
        Write-TestFail "TEST 6 FAILED: $_"
        $script:FailedTests++
        $script:TestResults += @{ Test = 6; Name = "Idempotency"; Status = "FAIL"; Error = $_.Exception.Message }
    }
}

# ─── Test 7: CI/CD Provider Skill Routing ─────────────────────────────────────

function Test-07-CicdProviderRouting {
        Write-TestHeader "TEST 7: CI/CD Provider Skill Routing"

        try {
                $setupScript = Join-Path $FrameworkRoot ".boltf\scripts\powershell\Invoke-BoltSetupConstitution.ps1"
                $cases = @(
                        @{ Platform = 'github-actions'; Expected = 'github-actions-templates'; Unexpected = 'skill-azdo-pipeline-templates' },
                        @{ Platform = 'azure-devops'; Expected = 'skill-azdo-pipeline-templates'; Unexpected = 'github-actions-templates' }
                )

                foreach ($case in $cases) {
                        $projectPath = New-TestProject ("test-07-cicd-" + $case.Platform)
                        Write-TestStep "Preparing project for platform: $($case.Platform)"

                        Copy-Item (Join-Path $FrameworkRoot '.boltf') $projectPath -Recurse -Force

                        $memoryDir = Join-Path $projectPath '.boltf\memory'
                        New-Item -ItemType Directory -Path $memoryDir -Force | Out-Null
                        Set-Content -Path (Join-Path $memoryDir 'constitution.md') -Value '# Project Constitution' -Encoding UTF8

                        $scopesYaml = @"
project:
    practice: Apps & Infra
    type: full-stack
    migration-type: green
    local-orchestration: none
    work-management-tool: none

active-scopes:
    - backend

transversal-scopes:
    - work-management

decisions:
    cicd:
        platform: $($case.Platform)
"@
                        Set-Content -Path (Join-Path $projectPath '.boltf\scopes.yaml') -Value $scopesYaml -Encoding UTF8

                        Write-TestStep "Running provisioning for $($case.Platform)..."
                        & $setupScript -ProjectPath $projectPath -Provision | Out-Null

                        $skillsDir = Join-Path $projectPath '.claude\skills'
                        Assert-FileExists (Join-Path $skillsDir 'skill-cicd-pipeline-azure\SKILL.md') "CI/CD orchestrator skill for $($case.Platform)"
                        Assert-FileExists (Join-Path $skillsDir "$($case.Expected)\SKILL.md") "Expected provider skill for $($case.Platform)"
                        Assert-FileNotExists (Join-Path $skillsDir "$($case.Unexpected)\SKILL.md") "Unexpected provider skill for $($case.Platform)"

                        Remove-TestProject $projectPath
                }

                Write-TestPass "TEST 7 PASSED"
                $script:PassedTests++
                $script:TestResults += @{ Test = 7; Name = "CI/CD Provider Routing"; Status = "PASS" }
        }
        catch {
                Write-TestFail "TEST 7 FAILED: $_"
                $script:FailedTests++
                $script:TestResults += @{ Test = 7; Name = "CI/CD Provider Routing"; Status = "FAIL"; Error = $_.Exception.Message }
        }
}

# ─── Main Test Runner ─────────────────────────────────────────────────────────

function Show-TestSummary {
    Write-Host "`n"
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Bolt Framework - Test Results Summary" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""

    foreach ($result in $TestResults) {
        $status = if ($result.Status -eq "PASS") { "✓" } else { "✗" }
        $color = if ($result.Status -eq "PASS") { "Green" } else { "Red" }

        Write-Host "  $status Test $($result.Test): $($result.Name)" -ForegroundColor $color
        if ($result.Error) {
            Write-Host "    Error: $($result.Error)" -ForegroundColor DarkGray
        }
    }

    Write-Host ""
    Write-Host "  Total: $($PassedTests + $FailedTests) tests" -ForegroundColor White
    Write-Host "  Passed: $PassedTests" -ForegroundColor Green
    Write-Host "  Failed: $FailedTests" -ForegroundColor $(if ($FailedTests -eq 0) { "Green" } else { "Red" })
    Write-Host ""

    if ($FailedTests -eq 0) {
        Write-Host "  ✓ ALL TESTS PASSED" -ForegroundColor Green
    } else {
        Write-Host "  ✗ SOME TESTS FAILED" -ForegroundColor Red
    }

    Write-Host "═══════════════════════════════════════════════════════════`n" -ForegroundColor Cyan
}

function Main {
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Bolt Framework - Two-Step Initialization Test Suite" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Framework Root: $FrameworkRoot" -ForegroundColor White
    Write-Host "  Test Output: $TestOutputDir" -ForegroundColor White
    if ($KeepTestProjects) {
        Write-Host "  Keep Projects: YES (for inspection)" -ForegroundColor Yellow
    }
    Write-Host ""

    # Create test output directory
    if (-not (Test-Path $TestOutputDir)) {
        New-Item -ItemType Directory -Path $TestOutputDir -Force | Out-Null
    }

    # Run tests
    if ($TestNumber -eq 0) {
        # Run all tests
        Test-01-AppsInfraInit
        Test-02-SetupConstitutionSkill
        Test-03-DataAIPractice
        Test-04-CustomMode
        Test-05-DryRunMode
        Test-06-Idempotency
        Test-07-CicdProviderRouting
    } else {
        # Run specific test
        switch ($TestNumber) {
            1 { Test-01-AppsInfraInit }
            2 { Test-02-SetupConstitutionSkill }
            3 { Test-03-DataAIPractice }
            4 { Test-04-CustomMode }
            5 { Test-05-DryRunMode }
            6 { Test-06-Idempotency }
            7 { Test-07-CicdProviderRouting }
            default { Write-Host "Invalid test number: $TestNumber (valid: 1-7)" -ForegroundColor Red; exit 1 }
        }
    }

    # Show summary
    Show-TestSummary

    # Exit with appropriate code
    if ($FailedTests -gt 0) {
        exit 1
    }
}

Main
