blank_issues_enabled: false
contact_links:
  - name: "💬 Discussions"
    url: https://github.com/Avanade-Region-Spain/train-bolt-framework-greenfield/discussions
    about: For general questions, ideas, or open-ended conversations, please use GitHub Discussions.
