#!/bin/bash
# =============================================================================
# Bolt Framework / AI-DLC - Feature Creation Script
# =============================================================================
# Creates a new feature branch and specification structure following
# the Bolt Framework methodology.
#
# Usage:
#   ./create-new-feature.sh <feature-name> [base-branch]
#
# Example:
#   ./create-new-feature.sh user-authentication main
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Validate arguments
if [ -z "$1" ]; then
    log_error "Feature name is required"
    echo "Usage: $0 <feature-name> [base-branch]"
    exit 1
fi

FEATURE_NAME="$1"
BASE_BRANCH="${2:-main}"
BRANCH_NAME="feature/${FEATURE_NAME}"
SPEC_DIR="specs/${FEATURE_NAME}"

log_info "Creating new feature: ${FEATURE_NAME}"
log_info "Base branch: ${BASE_BRANCH}"

# Check if git repository
if [ ! -d ".git" ]; then
    log_error "Not a git repository. Please run from project root."
    exit 1
fi

# Check if constitution exists
if [ ! -f ".boltf/memory/constitution.md" ]; then
    log_warning "Constitution not found at .boltf/memory/constitution.md"
    log_warning "Consider running /bolt.constitution first"
fi

# Create and checkout branch
log_info "Creating branch: ${BRANCH_NAME}"
git checkout "${BASE_BRANCH}"
git pull origin "${BASE_BRANCH}" 2>/dev/null || true
git checkout -b "${BRANCH_NAME}"

# Create specification directory structure
log_info "Creating specification structure..."
mkdir -p "${SPEC_DIR}/contracts"

# Create spec.md template
cat > "${SPEC_DIR}/spec.md" << 'EOF'
# Feature Specification: [Feature Name]

## Metadata

| Property | Value |
|----------|-------|
| Feature | [feature-name] |
| Author | [author] |
| Created | [date] |
| Status | Draft |
| Priority | P1/P2/P3 |

## Business Context

### Problem Statement

[Describe the business problem or opportunity this feature addresses]

### Expected Outcome

[Describe the expected business value and user benefit]

## User Stories

### US-001: [Story Title]

**As a** [role]
**I want** [action]
**So that** [benefit]

**Priority**: P1
**Effort**: S/M/L/XL

#### Acceptance Criteria

- [ ] AC1: [Criterion 1]
- [ ] AC2: [Criterion 2]
- [ ] AC3: [Criterion 3]

### US-002: [Story Title]

[Add more user stories as needed]

## Non-Functional Requirements

### Performance

- Response time P99: [X]ms
- Throughput: [X] requests/second

### Security

- [Security requirement 1]
- [Security requirement 2]

### Scalability

- [Scalability requirement]

## Out of Scope

- [Item 1]
- [Item 2]

## Dependencies

- [External system/feature dependency]

## Open Questions

- [ ] [Question 1]
- [ ] [Question 2]
EOF

# Create data-model.md template
cat > "${SPEC_DIR}/data-model.md" << 'EOF'
# Data Model: [Feature Name]

## Entities

### [Entity Name]

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| id | UUID | Yes | Unique identifier |
| createdAt | DateTime | Yes | Creation timestamp |
| updatedAt | DateTime | Yes | Last update timestamp |

#### Business Rules

1. [Rule 1]
2. [Rule 2]

## Relationships

```
[Entity A] 1──N [Entity B]
[Entity B] N──N [Entity C]
```

## Migrations

[Note any required database migrations]
EOF

# Create plan.md placeholder
cat > "${SPEC_DIR}/plan.md" << 'EOF'
# Implementation Plan: [Feature Name]

> This file will be generated by /bolt.plan

## Status

- [ ] Specification complete
- [ ] Plan generated
- [ ] Tasks generated
- [ ] Implementation started
EOF

# Create README for the spec directory
cat > "${SPEC_DIR}/README.md" << EOF
# ${FEATURE_NAME}

Specification directory for the ${FEATURE_NAME} feature.

## Files

| File | Purpose | Status |
|------|---------|--------|
| spec.md | Feature specification | 🔄 In Progress |
| data-model.md | Entity definitions | 📝 Template |
| plan.md | Implementation plan | ⏳ Pending |
| tasks.md | Task breakdown | ⏳ Pending |
| contracts/ | API specifications | ⏳ Pending |

## Workflow

1. Complete \`spec.md\` with user stories
2. Run \`/bolt.plan\` to generate plan
3. Run \`/bolt.tasks\` to generate task list
4. Run \`/bolt.implement\` to begin coding

## Branch

\`${BRANCH_NAME}\`
EOF

# Git operations
log_info "Committing initial structure..."
git add "${SPEC_DIR}"
git commit -m "feat(${FEATURE_NAME}): Initialize specification structure

- Created spec.md template
- Created data-model.md template
- Created plan.md placeholder
- Created contracts/ directory

Bolt Framework: UNDERSTAND phase started"

log_success "Feature branch and structure created!"
echo ""
echo "Next steps:"
echo "  1. Edit ${SPEC_DIR}/spec.md with requirements"
echo "  2. Edit ${SPEC_DIR}/data-model.md if entities exist"
echo "  3. Run /bolt.plan to generate implementation plan"
echo ""
echo "Branch: ${BRANCH_NAME}"
echo "Spec directory: ${SPEC_DIR}/"
