<#
.SYNOPSIS
    Bolt Framework / AI-DLC - Feature Creation Script

.DESCRIPTION
    Creates a new feature branch and specification structure following
    the Bolt Framework methodology.

.PARAMETER FeatureName
    The name of the feature to create.

.PARAMETER BaseBranch
    The base branch to create the feature from. Defaults to 'main'.

.EXAMPLE
    .\Create-NewFeature.ps1 -FeatureName "user-authentication"

.EXAMPLE
    .\Create-NewFeature.ps1 -FeatureName "order-management" -BaseBranch "develop"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$FeatureName,

    [Parameter(Mandatory=$false)]
    [string]$BaseBranch = "main"
)

# Colors and formatting
function Write-Info { Write-Host "[INFO] $args" -ForegroundColor Blue }
function Write-Success { Write-Host "[SUCCESS] $args" -ForegroundColor Green }
function Write-Warning { Write-Host "[WARNING] $args" -ForegroundColor Yellow }
function Write-Error { Write-Host "[ERROR] $args" -ForegroundColor Red }

$BranchName = "feature/$FeatureName"
$SpecDir = "specs/$FeatureName"

Write-Info "Creating new feature: $FeatureName"
Write-Info "Base branch: $BaseBranch"

# Check if git repository
if (-not (Test-Path ".git")) {
    Write-Error "Not a git repository. Please run from project root."
    exit 1
}

# Check if constitution exists
if (-not (Test-Path ".boltf/memory/constitution.md")) {
    Write-Warning "Constitution not found at .boltf/memory/constitution.md"
    Write-Warning "Consider running @Bolt Constitution first"
}

# Create and checkout branch
Write-Info "Creating branch: $BranchName"
try {
    git checkout $BaseBranch
    git pull origin $BaseBranch 2>$null
    git checkout -b $BranchName
} catch {
    Write-Error "Failed to create branch: $_"
    exit 1
}

# Create specification directory structure
Write-Info "Creating specification structure..."
New-Item -ItemType Directory -Path "$SpecDir/contracts" -Force | Out-Null

# Create spec.md template
$SpecContent = @'
# Feature Specification: [Feature Name]

## Metadata

| Property | Value |
|----------|-------|
| Feature | [feature-name] |
| Author | [author] |
| Created | [date] |
| Status | Draft |
| Priority | P1/P2/P3 |

## Business Context

### Problem Statement

[Describe the business problem or opportunity this feature addresses]

### Expected Outcome

[Describe the expected business value and user benefit]

## User Stories

### US-001: [Story Title]

**As a** [role]
**I want** [action]
**So that** [benefit]

**Priority**: P1
**Effort**: S/M/L/XL

#### Acceptance Criteria

- [ ] AC1: [Criterion 1]
- [ ] AC2: [Criterion 2]
- [ ] AC3: [Criterion 3]

### US-002: [Story Title]

[Add more user stories as needed]

## Non-Functional Requirements

### Performance

- Response time P99: [X]ms
- Throughput: [X] requests/second

### Security

- [Security requirement 1]
- [Security requirement 2]

### Scalability

- [Scalability requirement]

## Out of Scope

- [Item 1]
- [Item 2]

## Dependencies

- [External system/feature dependency]

## Open Questions

- [ ] [Question 1]
- [ ] [Question 2]
'@
Set-Content -Path "$SpecDir/spec.md" -Value $SpecContent

# Create data-model.md template
$DataModelContent = @'
# Data Model: [Feature Name]

## Entities

### [Entity Name]

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| id | UUID | Yes | Unique identifier |
| createdAt | DateTime | Yes | Creation timestamp |
| updatedAt | DateTime | Yes | Last update timestamp |

#### Business Rules

1. [Rule 1]
2. [Rule 2]

## Relationships

```
[Entity A] 1──N [Entity B]
[Entity B] N──N [Entity C]
```

## Migrations

[Note any required database migrations]
'@
Set-Content -Path "$SpecDir/data-model.md" -Value $DataModelContent

# Create plan.md placeholder
$PlanContent = @"
# Implementation Plan: [Feature Name]

> This file will be generated by @Bolt Plan

## Status

- [ ] Specification complete
- [ ] Plan generated
- [ ] Tasks generated
- [ ] Implementation started
"@
Set-Content -Path "$SpecDir/plan.md" -Value $PlanContent

# Create README for the spec directory
$ReadmeContent = @"
# $FeatureName

Specification directory for the $FeatureName feature.

## Files

| File | Purpose | Status |
|------|---------|--------|
| spec.md | Feature specification | :arrows_counterclockwise: In Progress |
| data-model.md | Entity definitions | :memo: Template |
| plan.md | Implementation plan | :hourglass: Pending |
| tasks.md | Task breakdown | :hourglass: Pending |
| contracts/ | API specifications | :hourglass: Pending |

## Workflow

1. Complete ``spec.md`` with user stories
2. Run ``@Bolt Plan`` to generate plan
3. Run ``@Bolt Tasks`` to generate task list
4. Run ``@Bolt Implement`` to begin coding

## Branch

``$BranchName``
"@
Set-Content -Path "$SpecDir/README.md" -Value $ReadmeContent

# Git operations
Write-Info "Committing initial structure..."
git add $SpecDir
git commit -m @"
feat($FeatureName): Initialize specification structure

- Created spec.md template
- Created data-model.md template
- Created plan.md placeholder
- Created contracts/ directory

Bolt Framework: UNDERSTAND phase started
"@

Write-Success "Feature branch and structure created!"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Edit $SpecDir/spec.md with requirements"
Write-Host "  2. Edit $SpecDir/data-model.md if entities exist"
Write-Host "  3. Run @Bolt Plan to generate implementation plan"
Write-Host ""
Write-Host "Branch: $BranchName"
Write-Host "Spec directory: $SpecDir/"
